import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header/header";
import Footer from "./components/footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col min-h-screen">
          <div className="text-white py-4 px-6 w-full h-20">
            <Header />
          </div>
          <div className="flex-grow overflow-y-auto">{children}</div>
          <div className="text-white py-4 h-20 w-full">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
